server:
    port: 2000
spring:
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            auto-offset-reset: latest
            group-id: shopee
            properties: {spring: {json: {trusted: {packages: com.shopee.tool}}}}
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            enable.auto.commit : false
        producer:
            value-serializer: org.apache.kafka.common.serialization.StringSerializer
cloud:
    topic:
        login:
            request: login-request
            response: login-response
        otp:
            request: otp-request
            response: otp-response
        follow:
            request: follow-request
            response: follow-response
        username:
            request: get-username-request
            response: get-username-response
        information-shop:
            request: information-shop-request
            response: information-shop-response
        items-shop:
            request: items-shop-request
            response: items-shop-response
        like-item:
            request: like-item-request
            response: like-item-response
        unfollow:
            request: unfollow-request
            response: unfollow-response
        unlike:
            request: unlike-request
            response: unlike-response
        view:
            request: view-request
            response: view-response
